#!/usr/bin/env python3
"""Headless greybox shot renderer for storyboard blocking.

Runs inside Blender:  Blender -b -P blender_shot.py -- --spec shot.json --out DIR

Takes a shot spec (camera, primitive or GLB subjects, ground, sun, optional camera
move) and produces two artefacts per shot:

  <name>_block.png   one still  — the composition reference
  <name>_move.mp4    short clip — the camera/subject motion reference

Both are deliberately CLAY, not pretty: Workbench engine, single-colour
matcap-ish shading with cavity. The point is geometry, scale and camera
truth that a video model can lock onto, not a render that competes with the
generated image. Workbench also needs no samples, so a shot renders in
seconds on CPU.

The spec is data, not code, so the same file can be regenerated by an agent,
diffed, and re-rendered without touching this script.
"""

import argparse
import json
import math
import os
import shutil
import subprocess
import sys

import bpy
from mathutils import Vector

# retarget.py sits beside this script; Blender's -P doesn't put it on the path.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Aspect strings the storyboard skill uses, as width/height multipliers.
ASPECTS = {
    "16:9": (16, 9),
    "9:16": (9, 16),
    "1:1": (1, 1),
    "4:5": (4, 5),
    "21:9": (21, 9),
    "2.39:1": (2.39, 1),
}


def argv_after_ddash():
    """Blender swallows its own args; ours live after a bare `--`."""
    return sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []


def wipe_scene():
    """Start from genuinely empty, not from Blender's default cube+lamp+cam."""
    bpy.ops.wm.read_factory_settings(use_empty=True)


def rotation_of(spec):
    """Euler rotation in radians from the spec's rot_x/rot_y/rot_z degrees.

    rot_z alone (yaw) cannot express a forearm angled into a macro frame or a
    canted surface, and faking those with extra geometry puts shapes in the
    render that the video model will faithfully reproduce as shapes.
    """
    return (
        math.radians(float(spec.get("rot_x") or 0.0)),
        math.radians(float(spec.get("rot_y") or 0.0)),
        math.radians(float(spec.get("rot_z") or 0.0)),
    )


def add_ground(size):
    bpy.ops.mesh.primitive_plane_add(size=size, location=(0, 0, 0))
    ground = bpy.context.active_object
    ground.name = "GROUND"
    return ground


def add_wall(loc, size, rot_z=0.0):
    """A vertical plane — backdrop, building face, canyon side."""
    bpy.ops.mesh.primitive_plane_add(size=1, location=loc)
    wall = bpy.context.active_object
    wall.name = "WALL"
    wall.rotation_euler = (math.radians(90), 0.0, math.radians(rot_z))
    wall.scale = (size[0], size[1], 1.0)
    return wall


def add_mannequin(name, loc, height, rot):
    """A human proxy from primitives.

    Scale truth is what makes a blocking render useful — a video model reading
    a greybox needs to see that the subject is 1.8 m against a 3 m doorway. A
    featureless capsule would give camera framing but no read on where a head
    or a shoulder line sits, so this is crude but jointed: head, torso, two
    legs, two arms, proportioned off `height`.

    Note on scale: these primitives are added at size=1, where an object's
    `scale` IS its dimension in metres (verified against bpy) — not a
    half-extent. Treating it as a half-extent silently builds everything at
    half size, which is exactly the kind of error a clay render exists to
    make visible.
    """
    h = float(height)
    parts = []

    # torso — shoulders land at 0.82h, just under the head
    bpy.ops.mesh.primitive_cube_add(size=1, location=(loc[0], loc[1], loc[2] + 0.66 * h))
    torso = bpy.context.active_object
    torso.scale = (0.26 * h, 0.15 * h, 0.32 * h)
    parts.append(torso)

    # head — crown sits at ~1.0h
    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.065 * h, location=(loc[0], loc[1], loc[2] + 0.93 * h))
    parts.append(bpy.context.active_object)

    for side in (-1, 1):
        # legs — ground to 0.50h, meeting the torso base
        bpy.ops.mesh.primitive_cylinder_add(
            radius=0.045 * h, depth=0.50 * h, location=(loc[0] + side * 0.06 * h, loc[1], loc[2] + 0.25 * h)
        )
        parts.append(bpy.context.active_object)
        # arms — hung just outside the torso's half width
        bpy.ops.mesh.primitive_cylinder_add(
            radius=0.032 * h, depth=0.38 * h, location=(loc[0] + side * 0.16 * h, loc[1], loc[2] + 0.60 * h)
        )
        parts.append(bpy.context.active_object)

    for part in parts:
        part.select_set(True)
    bpy.context.view_layer.objects.active = torso
    bpy.ops.object.join()
    body = bpy.context.active_object

    # join() leaves the origin wherever the active object's was — the torso
    # centre, ~0.66h off the ground. That origin is what `location` means, so
    # animating a figure to a spec `loc_end` of z=0 buried it up to the chest.
    # Re-origin to the feet: now `location` means the same thing for a figure
    # as for every other subject, rot_z turns about the body's own axis, and
    # loc_end needs no special case.
    bpy.context.scene.cursor.location = Vector((loc[0], loc[1], loc[2]))
    bpy.ops.object.origin_set(type="ORIGIN_CURSOR")
    bpy.context.scene.cursor.location = Vector((0.0, 0.0, 0.0))

    body.name = name
    body.rotation_euler = rot
    return body


def resolve_asset(path, spec_dir, cache_dir):
    """A local path (relative to the spec file) or an http(s) URL, as a local file.

    fal hands back GLBs as CDN URLs, so a spec can name the URL straight from
    the image-to-3D result. It is downloaded once into the output directory and
    reused on re-render, so iterating on a camera does not re-fetch a 30 MB mesh.
    """
    if path.startswith(("http://", "https://")):
        import hashlib
        import urllib.request

        os.makedirs(cache_dir, exist_ok=True)
        base = os.path.basename(path.split("?", 1)[0]) or "asset.glb"
        local = os.path.join(cache_dir, hashlib.sha1(path.encode()).hexdigest()[:10] + "_" + base)
        if not os.path.isfile(local):
            urllib.request.urlretrieve(path, local)
        return local
    path = os.path.expanduser(path)
    return path if os.path.isabs(path) else os.path.join(spec_dir, path)


def world_bounds(objs):
    """Axis-aligned world-space bounds over every mesh vertex in objs."""
    lo = Vector((math.inf, math.inf, math.inf))
    hi = Vector((-math.inf, -math.inf, -math.inf))
    for o in objs:
        if o.type != "MESH":
            continue
        for v in o.data.vertices:
            w = o.matrix_world @ v.co
            lo = Vector(map(min, lo, w))
            hi = Vector(map(max, hi, w))
    return lo, hi


def add_glb(name, spec, spec_dir, cache_dir):
    """A real mesh (e.g. an image-to-3D GLB) standing in for a primitive.

    Generated meshes arrive at arbitrary scale and with their origin wherever
    the generator put it, so the import is normalised before it is placed:

    - everything imported is parented to one empty, which is what `loc`,
      `rot_*` and `loc_end` move, exactly like a primitive;
    - the mesh is recentred so the empty sits at the bottom-centre of its
      bounds. `loc` therefore means the feet, as it does for `human`, and a
      car's `loc` is where its wheels touch the road;
    - `height` (metres, bounds z) or `length` (metres, longest horizontal
      side) sets a uniform scale; `scale` multiplies on top of either.

    glTF is +Y-up and faces +Z; Blender's importer turns that into Z-up
    facing -Y, i.e. towards a camera at negative y. `rot_z` turns it from
    there. Materials are left alone: Workbench's single-colour shading draws
    everything in clay regardless, which is the point of a greybox.

    `decimate` (0-1) thins a heavy mesh; image-to-3D output is often 500k
    faces, which renders fine but bloats every saved .blend.
    """
    path = resolve_asset(spec["path"], spec_dir, cache_dir)
    before = set(bpy.data.objects)
    bpy.ops.import_scene.gltf(filepath=path)
    imported = [o for o in bpy.data.objects if o not in before]
    meshes = [o for o in imported if o.type == "MESH"]
    if not meshes:
        raise RuntimeError(f"{path}: no mesh in GLB")

    ratio = spec.get("decimate")
    if ratio:
        for m in meshes:
            mod = m.modifiers.new("DECIMATE", "DECIMATE")
            mod.ratio = float(ratio)

    bpy.context.view_layer.update()
    lo, hi = world_bounds(meshes)
    dims = hi - lo
    factor = 1.0
    if spec.get("height"):
        factor = float(spec["height"]) / max(dims.z, 1e-6)
    elif spec.get("length"):
        factor = float(spec["length"]) / max(dims.x, dims.y, 1e-6)
    factor *= float(spec.get("scale") or 1.0)

    root = bpy.data.objects.new(name, None)
    bpy.context.scene.collection.objects.link(root)
    pivot = Vector(((lo.x + hi.x) / 2, (lo.y + hi.y) / 2, lo.z))
    for o in imported:
        if o.parent is None:
            # Keep world transform, then shift so the bounds' bottom-centre
            # lands on the empty's origin.
            o.parent = root
            o.matrix_parent_inverse = root.matrix_world.inverted()
            o.location -= pivot

    root.scale = (factor, factor, factor)
    root.location = spec.get("loc") or [0, 0, 0]
    root.rotation_euler = rotation_of(spec)
    return root


def add_rigged(name, spec, spec_dir, cache_dir, ctx):
    """A rigged character (Meshy Rigging GLB) performing a Hunyuan Motion clip.

    `path` is the rigged GLB, `anim` the Hunyuan Motion FBX; both may be URLs.
    The motion is retargeted onto the character's skeleton and baked on frames
    1..N of the shot (scripts/retarget.py), including the hips' travel, so a
    walk covers ground by itself: `loc` is where the character starts, not a
    slide target. `anim_offset` (seconds) starts partway into the clip; `in_place: true`
    keeps the hips' bob but drops the ground travel, for a performance that
    has to stay on its mark (a reaction in a close-up).

    Both rigs face -Y at rest (glTF and Hunyuan's FBX after import), the same
    convention as `glb`, so `rot_z` turns the whole performance, travel
    included. `loc_end` still works on top, but a walk rarely needs it.
    """
    import retarget

    scene = bpy.context.scene
    before = set(bpy.data.objects)
    bpy.ops.import_scene.gltf(filepath=resolve_asset(spec["path"], spec_dir, cache_dir))
    imported = [o for o in bpy.data.objects if o not in before]
    arm = next((o for o in imported if o.type == "ARMATURE"), None)
    if arm is None:
        raise RuntimeError(f"{spec['path']}: no armature, rig it first (Meshy Rigging)")
    skinned = [o for o in imported if o.type == "MESH" and any(m.type == "ARMATURE" for m in o.modifiers)]
    # Meshy ships a stray helper sphere and a default action; neither belongs in the shot.
    for o in imported:
        if o.type == "MESH" and o not in skinned:
            bpy.data.objects.remove(o, do_unlink=True)
    arm.animation_data_clear()
    for pb in arm.pose.bones:
        pb.matrix_basis.identity()

    root = bpy.data.objects.new(name, None)
    scene.collection.objects.link(root)
    arm.parent = root

    # The FBX importer rewrites the scene's fps and frame range to the clip's.
    keep = (scene.render.fps, scene.frame_start, scene.frame_end)
    before = set(bpy.data.objects)
    bpy.ops.import_scene.fbx(filepath=resolve_asset(spec["anim"], spec_dir, cache_dir))
    src_objs = [o for o in bpy.data.objects if o not in before]
    src_fps = scene.render.fps
    scene.render.fps, scene.frame_start, scene.frame_end = keep
    source = retarget.find_source_armature(src_objs)
    if source is None or not (source.animation_data and source.animation_data.action):
        raise RuntimeError(f"{spec['anim']}: no animated armature in the motion file")
    src_start = source.animation_data.action.frame_range[0]

    for o in skinned:  # skinning 200k verts per sampled frame is wasted work
        for m in o.modifiers:
            m.show_viewport = False
    mapped, scale, travel = retarget.bake(scene, arm, source, ctx["frames"], ctx["fps"], src_fps,
                                  src_start, float(spec.get("anim_offset") or 0.0),
                                          in_place=bool(spec.get("in_place")))
    for o in skinned:
        for m in o.modifiers:
            m.show_viewport = True
    for o in src_objs:
        bpy.data.objects.remove(o, do_unlink=True)

    ctx.setdefault("retargets", {})[name] = {"mapped_bones": mapped, "height_scale": round(scale, 3),
                                                   "travel_m": [round(v, 2) for v in travel]}
    s = float(spec.get("scale") or 1.0)
    root.scale = (s, s, s)
    root.location = spec.get("loc") or [0, 0, 0]
    root.rotation_euler = rotation_of(spec)
    return root


def expand_repeats(subjects):
    """`repeat: {count, offset}` lays out copies of a subject along a line.

    A street wants a lamp post every fifteen metres down both kerbs; writing
    twelve near-identical entries is how a spec gets a typo in post nine.
    Copies are named NAME_1, NAME_2, …; `loc_end` is shifted with them.
    """
    out = []
    for s in subjects:
        rep = s.get("repeat")
        if not rep:
            out.append(s)
            continue
        off = Vector(rep.get("offset") or [0, 0, 0])
        for i in range(int(rep.get("count") or 1)):
            c = {k: v for k, v in s.items() if k != "repeat"}
            c["name"] = f"{s.get('name') or 'REP'}_{i + 1}"
            c["loc"] = list(Vector(s.get("loc") or [0, 0, 0]) + off * i)
            if s.get("loc_end"):
                c["loc_end"] = list(Vector(s["loc_end"]) + off * i)
            out.append(c)
    return out


def add_subject(spec, spec_dir=".", cache_dir=".", ctx=None):
    kind = (spec.get("type") or "cube").lower()
    name = spec.get("name") or kind.upper()
    loc = spec.get("loc") or [0, 0, 0]
    size = spec.get("size") or [1, 1, 1]
    rot = rotation_of(spec)

    if kind in ("human", "figure", "mannequin", "person"):
        return add_mannequin(name, loc, float(spec.get("height") or size[2] or 1.8), rot)

    if kind in ("glb", "gltf", "mesh"):
        return add_glb(name, spec, spec_dir, cache_dir)

    if kind in ("rigged", "character"):
        return add_rigged(name, spec, spec_dir, cache_dir, ctx if ctx is not None else {})

    if kind == "cube" or kind == "box":
        bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
        obj = bpy.context.active_object
        obj.scale = (size[0], size[1], size[2])
    elif kind in ("cylinder", "column", "pillar"):
        bpy.ops.mesh.primitive_cylinder_add(radius=size[0] / 2, depth=size[2], location=loc)
        obj = bpy.context.active_object
    elif kind in ("sphere", "ball"):
        bpy.ops.mesh.primitive_uv_sphere_add(radius=size[0] / 2, location=loc)
        obj = bpy.context.active_object
    elif kind == "cone":
        bpy.ops.mesh.primitive_cone_add(radius1=size[0] / 2, depth=size[2], location=loc)
        obj = bpy.context.active_object
    elif kind == "plane":
        bpy.ops.mesh.primitive_plane_add(size=1, location=loc)
        obj = bpy.context.active_object
        obj.scale = (size[0], size[1], 1.0)
    elif kind == "wall":
        return add_wall(loc, size, float(spec.get("rot_z") or 0.0))
    else:
        bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
        obj = bpy.context.active_object
        obj.scale = (size[0], size[1], size[2])

    obj.name = name
    obj.rotation_euler = rot
    return obj


def setup_camera(cam_spec, target_empty):
    bpy.ops.object.camera_add(location=cam_spec.get("loc") or [0, -8, 1.7])
    cam = bpy.context.active_object
    cam.name = "SHOT_CAM"
    cam.data.lens = float(cam_spec.get("lens") or 35)
    # Track-to keeps aim declarative: the spec says what to look at, and the
    # animation only has to move two empties, never solve a rotation.
    con = cam.constraints.new(type="TRACK_TO")
    con.target = target_empty
    con.track_axis = "TRACK_NEGATIVE_Z"
    con.up_axis = "UP_Y"
    bpy.context.scene.camera = cam
    return cam


def setup_look_at(loc):
    bpy.ops.object.empty_add(type="PLAIN_AXES", location=loc)
    e = bpy.context.active_object
    e.name = "LOOK_AT"
    return e


def setup_sun(sun_spec, shading):
    """A real sun lamp, plus the Workbench switch that makes it count.

    Workbench normally lights with a fixed studio light and ignores every lamp
    in the scene, so a `sun` block in the spec would be decoration. Turning on
    use_scene_lights_render hands shading and shadow direction back to this
    lamp, which is the whole point of specifying a time of day per shot.
    """
    elev = math.radians(float(sun_spec.get("elevation_deg") or 45))
    azim = math.radians(float(sun_spec.get("azimuth_deg") or 35))
    bpy.ops.object.light_add(type="SUN", location=(0, 0, 10))
    sun = bpy.context.active_object
    sun.data.energy = float(sun_spec.get("strength") or 3.0)
    sun.data.angle = math.radians(float(sun_spec.get("softness_deg") or 3.0))
    sun.rotation_euler = (math.pi / 2 - elev, 0.0, azim)
    shading.use_scene_lights_render = True
    # Keep the studio light aimed with the sun for the ambient component.
    shading.studiolight_rotate_z = azim
    return sun


def setup_render(scene, aspect, width, clay_hex, sky_hex=None):
    w, h = ASPECTS.get(aspect, ASPECTS["16:9"])
    # Both dimensions forced even: h.264 with yuv420p refuses odd sizes, and
    # 9:16 at width 960 computes to 1707.
    scene.render.resolution_x = even(width)
    scene.render.resolution_y = even(round(width * h / w))
    scene.render.resolution_percentage = 100
    scene.render.engine = "BLENDER_WORKBENCH"

    shading = scene.display.shading
    shading.light = "STUDIO"
    shading.color_type = "SINGLE"
    shading.single_color = hex_to_rgb(clay_hex)
    shading.show_cavity = True
    shading.cavity_type = "BOTH"
    shading.show_shadows = True
    shading.shadow_intensity = 0.35
    # A dark silhouette edge on every object. Both audiences want it: the
    # director reads the blocking faster, and a video model conditioned on the
    # still gets an unambiguous object boundary instead of grey-on-grey.
    shading.show_object_outline = True
    shading.object_outline_color = (0.12, 0.12, 0.14)
    shading.show_specular_highlight = False
    # Set the backdrop explicitly — left on THEME, the sky is whatever the
    # user's Blender theme happens to be, which is not a reproducible render.
    shading.background_type = "VIEWPORT"
    shading.background_color = hex_to_rgb(sky_hex or "#dfe3e8")
    scene.display.render_aa = "8"
    scene.render.film_transparent = False
    return shading


def hex_to_rgb(h):
    h = (h or "#b8b8b8").lstrip("#")
    return tuple(int(h[i : i + 2], 16) / 255.0 for i in (0, 2, 4))


def even(n):
    """Round down to an even pixel count (h.264 yuv420p requires it)."""
    n = int(n)
    return n if n % 2 == 0 else n - 1


def find_ffmpeg():
    """An encoder on PATH, or the usual Homebrew spot.

    Blender's own FFMPEG output is a build-time option and this machine's
    build does not have it (its file_format enum lists only image formats),
    so the clip is rendered as a PNG sequence and encoded outside Blender.
    That is the more portable arrangement regardless: it does not depend on
    how anyone's Blender was compiled.
    """
    found = shutil.which("ffmpeg")
    if found:
        return found
    for candidate in ("/opt/homebrew/bin/ffmpeg", "/usr/local/bin/ffmpeg"):
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return None


def encode_clip(frames_dir, pattern, fps, dest):
    """PNG sequence -> mp4. Returns None on success, else a reason string."""
    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        return "no ffmpeg on PATH — install it (brew install ffmpeg) for motion references"
    cmd = [
        ffmpeg, "-y", "-loglevel", "error",
        "-framerate", str(fps),
        "-i", os.path.join(frames_dir, pattern),
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20",
        "-movflags", "+faststart",
        dest,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        return (proc.stderr or "ffmpeg failed").strip()[:400]
    return None


def action_fcurves(holder):
    """Every F-curve on an object's action, across Blender action APIs.

    Blender 4.4 moved F-curves behind slotted actions
    (action.layers[].strips[].channelbags[].fcurves) and dropped the flat
    `action.fcurves` that every older script used. Support both so this
    renders on 4.x and 5.x without a version check at the call site.
    """
    ad = getattr(holder, "animation_data", None)
    action = getattr(ad, "action", None) if ad else None
    if action is None:
        return []
    flat = getattr(action, "fcurves", None)
    if flat is not None:
        return list(flat)
    out = []
    for layer in getattr(action, "layers", []):
        for strip in getattr(layer, "strips", []):
            for bag in getattr(strip, "channelbags", []):
                out.extend(getattr(bag, "fcurves", []))
    return out


def ease(holder):
    """Ease every key so a move reads as an operator, not a robot slide."""
    for fc in action_fcurves(holder):
        for kp in fc.keyframe_points:
            kp.interpolation = "BEZIER"
            kp.easing = "EASE_IN_OUT"


def animate_camera(scene, cam, look_at, spec, frames):
    """Keyframe the camera move: start pose at frame 1, end pose at the last.

    Only the two objects the TRACK_TO arrangement needs are animated, so a
    'move' is expressed in the spec as a second camera pose rather than as a
    curve. Enough for a motion reference; deliberately not a full animation
    system.
    """
    end = spec.get("camera_end")
    scene.frame_start = 1
    scene.frame_end = frames

    cam.location = Vector(spec["camera"].get("loc") or [0, -8, 1.7])
    cam.keyframe_insert("location", frame=1)
    look_at.location = Vector(spec["camera"].get("look_at") or [0, 0, 1.2])
    look_at.keyframe_insert("location", frame=1)
    cam.data.lens = float(spec["camera"].get("lens") or 35)
    cam.data.keyframe_insert("lens", frame=1)

    if end:
        cam.location = Vector(end.get("loc") or spec["camera"].get("loc") or [0, -8, 1.7])
        cam.keyframe_insert("location", frame=frames)
        look_at.location = Vector(end.get("look_at") or spec["camera"].get("look_at") or [0, 0, 1.2])
        look_at.keyframe_insert("location", frame=frames)
        cam.data.lens = float(end.get("lens") or spec["camera"].get("lens") or 35)
        cam.data.keyframe_insert("lens", frame=frames)

    for holder in (cam, cam.data, look_at):
        ease(holder)


def linear(holder):
    """Constant speed: a car driving through frame doesn't pull away from a stop."""
    for fc in action_fcurves(holder):
        for kp in fc.keyframe_points:
            kp.interpolation = "LINEAR"


def animate_subjects(scene, movers, frames):
    """A subject with `loc_end` slides from loc to loc_end over the clip.

    Eased by default, like a person setting off and stopping; `"motion":
    "linear"` keeps a constant speed, which is what a passing vehicle needs
    when only the camera is meant to whip.
    """
    for obj, end_loc, motion in movers:
        obj.keyframe_insert("location", frame=1)
        obj.location = Vector(end_loc)
        obj.keyframe_insert("location", frame=frames)
        (linear if motion == "linear" else ease)(obj)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True, help="shot spec JSON path")
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--still-only", action="store_true", help="skip the mp4")
    args = ap.parse_args(argv_after_ddash())

    with open(args.spec) as f:
        spec = json.load(f)

    name = spec.get("name") or "SHOT"
    aspect = spec.get("aspect") or "16:9"
    width = spec.get("width") or 960
    fps = int(spec.get("fps") or 24)
    duration = float(spec.get("duration") or 2.5)
    frames = max(2, int(round(fps * duration)))

    os.makedirs(args.out, exist_ok=True)
    wipe_scene()
    scene = bpy.context.scene
    scene.render.fps = fps
    shading = setup_render(scene, aspect, width, spec.get("clay_color"), spec.get("sky_color"))

    if spec.get("ground", True):
        add_ground(float(spec.get("ground_size") or 60))

    spec_dir = os.path.dirname(os.path.abspath(args.spec))
    cache_dir = os.path.join(args.out, "_assets")
    ctx = {"frames": frames, "fps": fps}
    movers = []
    for subject in expand_repeats(spec.get("subjects") or []):
        obj = add_subject(subject, spec_dir, cache_dir, ctx)
        if subject.get("loc_end"):
            # Move by the delta the spec asks for, not to a raw coordinate, so
            # the object's own origin convention is irrelevant.
            start = Vector(subject.get("loc") or [0, 0, 0])
            delta = Vector(subject["loc_end"]) - start
            movers.append((obj, obj.location + delta, subject.get("motion")))

    look_at = setup_look_at(spec.get("camera", {}).get("look_at") or [0, 0, 1.2])
    cam = setup_camera(spec.get("camera") or {}, look_at)
    setup_sun(spec.get("sun") or {}, shading)

    animate_camera(scene, cam, look_at, spec, frames)
    animate_subjects(scene, movers, frames)

    out = {"name": name}
    if ctx.get("retargets"):
        out["retargets"] = ctx["retargets"]

    # --- still: frame 1, the composition reference -----------------------
    still = os.path.join(args.out, f"{name}_block.png")
    scene.frame_set(1)
    scene.render.image_settings.file_format = "PNG"
    scene.render.filepath = still
    bpy.ops.render.render(write_still=True)
    out["still"] = still

    # --- clip: the motion reference --------------------------------------
    if not args.still_only:
        clip = os.path.join(args.out, f"{name}_move.mp4")
        frames_dir = os.path.join(args.out, f"{name}_frames")
        os.makedirs(frames_dir, exist_ok=True)
        scene.render.image_settings.file_format = "PNG"
        scene.render.filepath = os.path.join(frames_dir, "f_")
        bpy.ops.render.render(animation=True)

        problem = encode_clip(frames_dir, "f_%04d.png", fps, clip)
        if problem:
            # The sequence is left behind on failure so the frames are not lost
            # to a missing encoder; on success it is noise.
            out["clip_error"] = problem
            out["frames_dir"] = frames_dir
        else:
            shutil.rmtree(frames_dir, ignore_errors=True)
            out["clip"] = clip
            out["frames"] = frames
            out["fps"] = fps

    blend = os.path.join(args.out, f"{name}.blend")
    bpy.ops.wm.save_as_mainfile(filepath=blend)
    out["blend"] = blend
    out["resolution"] = [scene.render.resolution_x, scene.render.resolution_y]

    print("SHOT_RESULT " + json.dumps(out))


if __name__ == "__main__":
    main()
