#!/usr/bin/env python3
"""Headless greybox shot renderer for storyboard blocking.

Runs inside Blender:  Blender -b -P blender_shot.py -- --spec shot.json --out DIR

Takes a shot spec (camera, primitive subjects, ground, sun, optional camera
move) and produces two artefacts per shot:

  <name>_block.png   one still  — the composition reference
  <name>_move.mp4    short clip — the camera/subject motion reference

Both are deliberately CLAY, not pretty: Workbench engine, single-colour
matcap-ish shading with cavity. The point is geometry, scale and camera
truth that a video model can lock onto, not a render that competes with the
generated image. Workbench also needs no samples, so a shot renders in
seconds on CPU.

The spec is data, not code, so the same file can be regenerated by an agent,
diffed, and re-rendered without touching this script.
"""

import argparse
import json
import math
import os
import shutil
import subprocess
import sys

import bpy
from mathutils import Vector

# Aspect strings the storyboard skill uses, as width/height multipliers.
ASPECTS = {
    "16:9": (16, 9),
    "9:16": (9, 16),
    "1:1": (1, 1),
    "4:5": (4, 5),
    "21:9": (21, 9),
    "2.39:1": (2.39, 1),
}


def argv_after_ddash():
    """Blender swallows its own args; ours live after a bare `--`."""
    return sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []


def wipe_scene():
    """Start from genuinely empty, not from Blender's default cube+lamp+cam."""
    bpy.ops.wm.read_factory_settings(use_empty=True)


def rotation_of(spec):
    """Euler rotation in radians from the spec's rot_x/rot_y/rot_z degrees.

    rot_z alone (yaw) cannot express a forearm angled into a macro frame or a
    canted surface, and faking those with extra geometry puts shapes in the
    render that the video model will faithfully reproduce as shapes.
    """
    return (
        math.radians(float(spec.get("rot_x") or 0.0)),
        math.radians(float(spec.get("rot_y") or 0.0)),
        math.radians(float(spec.get("rot_z") or 0.0)),
    )


def add_ground(size):
    bpy.ops.mesh.primitive_plane_add(size=size, location=(0, 0, 0))
    ground = bpy.context.active_object
    ground.name = "GROUND"
    return ground


def add_wall(loc, size, rot_z=0.0):
    """A vertical plane — backdrop, building face, canyon side."""
    bpy.ops.mesh.primitive_plane_add(size=1, location=loc)
    wall = bpy.context.active_object
    wall.name = "WALL"
    wall.rotation_euler = (math.radians(90), 0.0, math.radians(rot_z))
    wall.scale = (size[0], size[1], 1.0)
    return wall


def add_mannequin(name, loc, height, rot):
    """A human proxy from primitives.

    Scale truth is what makes a blocking render useful — a video model reading
    a greybox needs to see that the subject is 1.8 m against a 3 m doorway. A
    featureless capsule would give camera framing but no read on where a head
    or a shoulder line sits, so this is crude but jointed: head, torso, two
    legs, two arms, proportioned off `height`.

    Note on scale: these primitives are added at size=1, where an object's
    `scale` IS its dimension in metres (verified against bpy) — not a
    half-extent. Treating it as a half-extent silently builds everything at
    half size, which is exactly the kind of error a clay render exists to
    make visible.
    """
    h = float(height)
    parts = []

    # torso — shoulders land at 0.82h, just under the head
    bpy.ops.mesh.primitive_cube_add(size=1, location=(loc[0], loc[1], loc[2] + 0.66 * h))
    torso = bpy.context.active_object
    torso.scale = (0.26 * h, 0.15 * h, 0.32 * h)
    parts.append(torso)

    # head — crown sits at ~1.0h
    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.065 * h, location=(loc[0], loc[1], loc[2] + 0.93 * h))
    parts.append(bpy.context.active_object)

    for side in (-1, 1):
        # legs — ground to 0.50h, meeting the torso base
        bpy.ops.mesh.primitive_cylinder_add(
            radius=0.045 * h, depth=0.50 * h, location=(loc[0] + side * 0.06 * h, loc[1], loc[2] + 0.25 * h)
        )
        parts.append(bpy.context.active_object)
        # arms — hung just outside the torso's half width
        bpy.ops.mesh.primitive_cylinder_add(
            radius=0.032 * h, depth=0.38 * h, location=(loc[0] + side * 0.16 * h, loc[1], loc[2] + 0.60 * h)
        )
        parts.append(bpy.context.active_object)

    for part in parts:
        part.select_set(True)
    bpy.context.view_layer.objects.active = torso
    bpy.ops.object.join()
    body = bpy.context.active_object

    # join() leaves the origin wherever the active object's was — the torso
    # centre, ~0.66h off the ground. That origin is what `location` means, so
    # animating a figure to a spec `loc_end` of z=0 buried it up to the chest.
    # Re-origin to the feet: now `location` means the same thing for a figure
    # as for every other subject, rot_z turns about the body's own axis, and
    # loc_end needs no special case.
    bpy.context.scene.cursor.location = Vector((loc[0], loc[1], loc[2]))
    bpy.ops.object.origin_set(type="ORIGIN_CURSOR")
    bpy.context.scene.cursor.location = Vector((0.0, 0.0, 0.0))

    body.name = name
    body.rotation_euler = rot
    return body


def add_subject(spec):
    kind = (spec.get("type") or "cube").lower()
    name = spec.get("name") or kind.upper()
    loc = spec.get("loc") or [0, 0, 0]
    size = spec.get("size") or [1, 1, 1]
    rot = rotation_of(spec)

    if kind in ("human", "figure", "mannequin", "person"):
        return add_mannequin(name, loc, float(spec.get("height") or size[2] or 1.8), rot)

    if kind == "cube" or kind == "box":
        bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
        obj = bpy.context.active_object
        obj.scale = (size[0], size[1], size[2])
    elif kind in ("cylinder", "column", "pillar"):
        bpy.ops.mesh.primitive_cylinder_add(radius=size[0] / 2, depth=size[2], location=loc)
        obj = bpy.context.active_object
    elif kind in ("sphere", "ball"):
        bpy.ops.mesh.primitive_uv_sphere_add(radius=size[0] / 2, location=loc)
        obj = bpy.context.active_object
    elif kind == "cone":
        bpy.ops.mesh.primitive_cone_add(radius1=size[0] / 2, depth=size[2], location=loc)
        obj = bpy.context.active_object
    elif kind == "plane":
        bpy.ops.mesh.primitive_plane_add(size=1, location=loc)
        obj = bpy.context.active_object
        obj.scale = (size[0], size[1], 1.0)
    elif kind == "wall":
        return add_wall(loc, size, float(spec.get("rot_z") or 0.0))
    else:
        bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
        obj = bpy.context.active_object
        obj.scale = (size[0], size[1], size[2])

    obj.name = name
    obj.rotation_euler = rot
    return obj


def setup_camera(cam_spec, target_empty):
    bpy.ops.object.camera_add(location=cam_spec.get("loc") or [0, -8, 1.7])
    cam = bpy.context.active_object
    cam.name = "SHOT_CAM"
    cam.data.lens = float(cam_spec.get("lens") or 35)
    # Track-to keeps aim declarative: the spec says what to look at, and the
    # animation only has to move two empties, never solve a rotation.
    con = cam.constraints.new(type="TRACK_TO")
    con.target = target_empty
    con.track_axis = "TRACK_NEGATIVE_Z"
    con.up_axis = "UP_Y"
    bpy.context.scene.camera = cam
    return cam


def setup_look_at(loc):
    bpy.ops.object.empty_add(type="PLAIN_AXES", location=loc)
    e = bpy.context.active_object
    e.name = "LOOK_AT"
    return e


def setup_sun(sun_spec, shading):
    """A real sun lamp, plus the Workbench switch that makes it count.

    Workbench normally lights with a fixed studio light and ignores every lamp
    in the scene, so a `sun` block in the spec would be decoration. Turning on
    use_scene_lights_render hands shading and shadow direction back to this
    lamp, which is the whole point of specifying a time of day per shot.
    """
    elev = math.radians(float(sun_spec.get("elevation_deg") or 45))
    azim = math.radians(float(sun_spec.get("azimuth_deg") or 35))
    bpy.ops.object.light_add(type="SUN", location=(0, 0, 10))
    sun = bpy.context.active_object
    sun.data.energy = float(sun_spec.get("strength") or 3.0)
    sun.data.angle = math.radians(float(sun_spec.get("softness_deg") or 3.0))
    sun.rotation_euler = (math.pi / 2 - elev, 0.0, azim)
    shading.use_scene_lights_render = True
    # Keep the studio light aimed with the sun for the ambient component.
    shading.studiolight_rotate_z = azim
    return sun


def setup_render(scene, aspect, width, clay_hex, sky_hex=None):
    w, h = ASPECTS.get(aspect, ASPECTS["16:9"])
    # Both dimensions forced even: h.264 with yuv420p refuses odd sizes, and
    # 9:16 at width 960 computes to 1707.
    scene.render.resolution_x = even(width)
    scene.render.resolution_y = even(round(width * h / w))
    scene.render.resolution_percentage = 100
    scene.render.engine = "BLENDER_WORKBENCH"

    shading = scene.display.shading
    shading.light = "STUDIO"
    shading.color_type = "SINGLE"
    shading.single_color = hex_to_rgb(clay_hex)
    shading.show_cavity = True
    shading.cavity_type = "BOTH"
    shading.show_shadows = True
    shading.shadow_intensity = 0.35
    # A dark silhouette edge on every object. Both audiences want it: the
    # director reads the blocking faster, and a video model conditioned on the
    # still gets an unambiguous object boundary instead of grey-on-grey.
    shading.show_object_outline = True
    shading.object_outline_color = (0.12, 0.12, 0.14)
    shading.show_specular_highlight = False
    # Set the backdrop explicitly — left on THEME, the sky is whatever the
    # user's Blender theme happens to be, which is not a reproducible render.
    shading.background_type = "VIEWPORT"
    shading.background_color = hex_to_rgb(sky_hex or "#dfe3e8")
    scene.display.render_aa = "8"
    scene.render.film_transparent = False
    return shading


def hex_to_rgb(h):
    h = (h or "#b8b8b8").lstrip("#")
    return tuple(int(h[i : i + 2], 16) / 255.0 for i in (0, 2, 4))


def even(n):
    """Round down to an even pixel count (h.264 yuv420p requires it)."""
    n = int(n)
    return n if n % 2 == 0 else n - 1


def find_ffmpeg():
    """An encoder on PATH, or the usual Homebrew spot.

    Blender's own FFMPEG output is a build-time option and this machine's
    build does not have it (its file_format enum lists only image formats),
    so the clip is rendered as a PNG sequence and encoded outside Blender.
    That is the more portable arrangement regardless: it does not depend on
    how anyone's Blender was compiled.
    """
    found = shutil.which("ffmpeg")
    if found:
        return found
    for candidate in ("/opt/homebrew/bin/ffmpeg", "/usr/local/bin/ffmpeg"):
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return None


def encode_clip(frames_dir, pattern, fps, dest):
    """PNG sequence -> mp4. Returns None on success, else a reason string."""
    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        return "no ffmpeg on PATH — install it (brew install ffmpeg) for motion references"
    cmd = [
        ffmpeg, "-y", "-loglevel", "error",
        "-framerate", str(fps),
        "-i", os.path.join(frames_dir, pattern),
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20",
        "-movflags", "+faststart",
        dest,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        return (proc.stderr or "ffmpeg failed").strip()[:400]
    return None


def action_fcurves(holder):
    """Every F-curve on an object's action, across Blender action APIs.

    Blender 4.4 moved F-curves behind slotted actions
    (action.layers[].strips[].channelbags[].fcurves) and dropped the flat
    `action.fcurves` that every older script used. Support both so this
    renders on 4.x and 5.x without a version check at the call site.
    """
    ad = getattr(holder, "animation_data", None)
    action = getattr(ad, "action", None) if ad else None
    if action is None:
        return []
    flat = getattr(action, "fcurves", None)
    if flat is not None:
        return list(flat)
    out = []
    for layer in getattr(action, "layers", []):
        for strip in getattr(layer, "strips", []):
            for bag in getattr(strip, "channelbags", []):
                out.extend(getattr(bag, "fcurves", []))
    return out


def ease(holder):
    """Ease every key so a move reads as an operator, not a robot slide."""
    for fc in action_fcurves(holder):
        for kp in fc.keyframe_points:
            kp.interpolation = "BEZIER"
            kp.easing = "EASE_IN_OUT"


def animate_camera(scene, cam, look_at, spec, frames):
    """Keyframe the camera move: start pose at frame 1, end pose at the last.

    Only the two objects the TRACK_TO arrangement needs are animated, so a
    'move' is expressed in the spec as a second camera pose rather than as a
    curve. Enough for a motion reference; deliberately not a full animation
    system.
    """
    end = spec.get("camera_end")
    scene.frame_start = 1
    scene.frame_end = frames

    cam.location = Vector(spec["camera"].get("loc") or [0, -8, 1.7])
    cam.keyframe_insert("location", frame=1)
    look_at.location = Vector(spec["camera"].get("look_at") or [0, 0, 1.2])
    look_at.keyframe_insert("location", frame=1)
    cam.data.lens = float(spec["camera"].get("lens") or 35)
    cam.data.keyframe_insert("lens", frame=1)

    if end:
        cam.location = Vector(end.get("loc") or spec["camera"].get("loc") or [0, -8, 1.7])
        cam.keyframe_insert("location", frame=frames)
        look_at.location = Vector(end.get("look_at") or spec["camera"].get("look_at") or [0, 0, 1.2])
        look_at.keyframe_insert("location", frame=frames)
        cam.data.lens = float(end.get("lens") or spec["camera"].get("lens") or 35)
        cam.data.keyframe_insert("lens", frame=frames)

    for holder in (cam, cam.data, look_at):
        ease(holder)


def animate_subjects(scene, movers, frames):
    """A subject with `loc_end` slides from loc to loc_end over the clip."""
    for obj, end_loc in movers:
        obj.keyframe_insert("location", frame=1)
        obj.location = Vector(end_loc)
        obj.keyframe_insert("location", frame=frames)
        ease(obj)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True, help="shot spec JSON path")
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--still-only", action="store_true", help="skip the mp4")
    args = ap.parse_args(argv_after_ddash())

    with open(args.spec) as f:
        spec = json.load(f)

    name = spec.get("name") or "SHOT"
    aspect = spec.get("aspect") or "16:9"
    width = spec.get("width") or 960
    fps = int(spec.get("fps") or 24)
    duration = float(spec.get("duration") or 2.5)
    frames = max(2, int(round(fps * duration)))

    os.makedirs(args.out, exist_ok=True)
    wipe_scene()
    scene = bpy.context.scene
    scene.render.fps = fps
    shading = setup_render(scene, aspect, width, spec.get("clay_color"), spec.get("sky_color"))

    if spec.get("ground", True):
        add_ground(float(spec.get("ground_size") or 60))

    movers = []
    for subject in spec.get("subjects") or []:
        obj = add_subject(subject)
        if subject.get("loc_end"):
            # Move by the delta the spec asks for, not to a raw coordinate, so
            # the object's own origin convention is irrelevant.
            start = Vector(subject.get("loc") or [0, 0, 0])
            delta = Vector(subject["loc_end"]) - start
            movers.append((obj, obj.location + delta))

    look_at = setup_look_at(spec.get("camera", {}).get("look_at") or [0, 0, 1.2])
    cam = setup_camera(spec.get("camera") or {}, look_at)
    setup_sun(spec.get("sun") or {}, shading)

    animate_camera(scene, cam, look_at, spec, frames)
    animate_subjects(scene, movers, frames)

    out = {"name": name}

    # --- still: frame 1, the composition reference -----------------------
    still = os.path.join(args.out, f"{name}_block.png")
    scene.frame_set(1)
    scene.render.image_settings.file_format = "PNG"
    scene.render.filepath = still
    bpy.ops.render.render(write_still=True)
    out["still"] = still

    # --- clip: the motion reference --------------------------------------
    if not args.still_only:
        clip = os.path.join(args.out, f"{name}_move.mp4")
        frames_dir = os.path.join(args.out, f"{name}_frames")
        os.makedirs(frames_dir, exist_ok=True)
        scene.render.image_settings.file_format = "PNG"
        scene.render.filepath = os.path.join(frames_dir, "f_")
        bpy.ops.render.render(animation=True)

        problem = encode_clip(frames_dir, "f_%04d.png", fps, clip)
        if problem:
            # The sequence is left behind on failure so the frames are not lost
            # to a missing encoder; on success it is noise.
            out["clip_error"] = problem
            out["frames_dir"] = frames_dir
        else:
            shutil.rmtree(frames_dir, ignore_errors=True)
            out["clip"] = clip
            out["frames"] = frames
            out["fps"] = fps

    blend = os.path.join(args.out, f"{name}.blend")
    bpy.ops.wm.save_as_mainfile(filepath=blend)
    out["blend"] = blend
    out["resolution"] = [scene.render.resolution_x, scene.render.resolution_y]

    print("SHOT_RESULT " + json.dumps(out))


if __name__ == "__main__":
    main()
